### ISSUE TITLE
cargo run -- serve broken on macOS High Sierra

### ISSUE THREAD

**Issue by DorianListens** [steveklabnik/doxidize#101]
Running doxidize locally on macOS high sierra 10.13.4 returns "incorrect path" for every request, including the one output on the command line (http://127.0.0.1:7878/doxidize/index.html).

nightly-2018-04-01-x86_64-apple-darwin (default)
rustc 1.26.0-nightly (517f24025 2018-03-31)

**Comment by lqd** [comment]
The behaviour is similar on Sierra, but this URL should work: http://127.0.0.1:7878/public/doxidize/index.html

**Comment by austinglaser** [comment]
Same behavior on ubuntu 16.04
