### ISSUE TITLE
navigating to a new page resets sidebar open/closed state

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/doxidize#40]
probably should localstorage that

**Comment by fbstj** [comment]
is this covering "navigating to user guides pages still shows the getting-started page open"?

**Comment by steveklabnik** [comment]
Yup!

**Comment by gnzlbg** [comment]
#94 looks related to this one.

**Comment by mgattozzi** [comment]
I think #73 will also need to be closed then unless there's still a flash.
