### ISSUE TITLE
Not working on Windows?

### ISSUE THREAD

**Issue by jonathandturner** [steveklabnik/doxidize#92]
Sorry if I'm missing a step, but I currently tried to get this working on Windows and am seeing:

```
C:\Users\Jonathan\thirdparty\doxidize>cargo run -- build
    Updating git repository `https://github.com/steveklabnik/simple-server`
error: failed to load source for a dependency on `simple-server`

Caused by:
  Unable to update https://github.com/steveklabnik/simple-server?branch=gh96#502fc3f1

Caused by:
  revspec '502fc3f101df65795ac221bf123c1418f062b7d2' not found; class=Reference (4); code=NotFound (-3)
```

Any idea what might cause that?  Might be Windows related (or, I may have missed something)

**Comment by jonathandturner** [comment]
I'm seeing the same thing in Linux as well.

**Comment by mgattozzi** [comment]
It's because simple-server does not have the gh96 branch anymore. Until simple-server is released or this tracks master it's busted. Simmilar to https://github.com/steveklabnik/doxidize/issues/91

**Comment by jonathandturner** [comment]
@mgattozzi - is there a way to workaround the issue for now?

**Comment by steveklabnik** [comment]
just pushed a commit to fix this
