### ISSUE TITLE
Tests fail due to a branch in simple-server that doesn't exist

### ISSUE THREAD

**Issue by tirkarthi** [steveklabnik/doxidize#93]
Tests fail due to using a branch (gh96) from simple-server repo that doesn't exist. 

https://github.com/steveklabnik/doxidize/blob/master/Cargo.toml#L39

Build failure : https://travis-ci.org/steveklabnik/doxidize/builds/359890935

There is already a PR to use Travis CI #89 . Feel free to close this if it's not necessary.

Thanks

**Comment by steveklabnik** [comment]
See #92

**Comment by tirkarthi** [comment]
Sorry about that. I overlooked the issue thinking it was windows specific. Closing it in favour of #92 and #91 .

Thanks
